services:
  - type: web
    name: dconaninfosearch
    env: python
    region: oregon
    plan: free
    buildCommand: |
      git submodule update --init --recursive
      pip install -r requirements.txt
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: GIT_SUBMODULE_SSH_KEY
        value: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          ...
          -----END OPENSSH PRIVATE KEY-----
