services:
  - type: web
    name: dconaninfosearch
    env: python
    buildCommand: |
      git submodule update --init --recursive
      pip install -r requirements.txt
    startCommand: "python app.py"
    envVars:
      - key: GIT_SUBMODULE_SSH_KEY
        sync: false  
